INSERT INTO STUDENT VALUES (1, 'Leonardo');
INSERT INTO STUDENT VALUES (2, 'Rick');
INSERT INTO STUDENT VALUES (3, 'Samantha');
INSERT INTO STUDENT VALUES (4, 'Julia');
INSERT INTO STUDENT VALUES (5, 'Arun');
INSERT INTO STUDENT VALUES (6, 'John');

INSERT INTO COURSE VALUES (1, 'Biology');
INSERT INTO COURSE VALUES (2, 'Math');
INSERT INTO COURSE VALUES (3, 'Programming');
INSERT INTO COURSE VALUES (4, 'Advanced data structures');
INSERT INTO COURSE VALUES (5, 'Economics');

INSERT INTO STUDENT_COURSE_REGISTRATION VALUES (1, 3, 1);
INSERT INTO STUDENT_COURSE_REGISTRATION VALUES (2, 3, 2);
INSERT INTO STUDENT_COURSE_REGISTRATION VALUES (3, 3, 5);
INSERT INTO STUDENT_COURSE_REGISTRATION VALUES(4, 5, 3);

INSERT INTO STUDENT_COURSE_SCORE VALUES(1, 9.00, 1);
INSERT INTO STUDENT_COURSE_SCORE VALUES(2, 9.00, 2);
INSERT INTO STUDENT_COURSE_SCORE VALUES(3, 7.50, 3);